WITH INUT AS
 (SELECT TRUNC(DTAHORINUTILIZACAO, 'MM') MES, COUNT(*) QTD_INUT
    FROM MONITORPDV.TB_DOCTOINUTNFE
   WHERE CODRETORNO = 102
     AND DTAHORINUTILIZACAO BETWEEN DATE '2025-01-01' AND SYSDATE
     AND NROEMPRESA = 8
   GROUP BY TRUNC(DTAHORINUTILIZACAO, 'MM')),
   
NORMAL AS
 (SELECT TRUNC(Y.DTAMOVIMENTO, 'MM') MES, COUNT(*) QTD_NORMAL
    FROM MONITORPDV.TB_DOCTO Y INNER JOIN MONITORPDV.TB_DOCTONFEXML X ON X.NROEMPRESA = Y.NROEMPRESA AND X.NROCHECKOUT = Y.NROCHECKOUT AND X.SEQDOCTO = Y.SEQDOCTO
                               INNER JOIN MONITORPDV.TB_DOCTONFE N    ON N.NROEMPRESA = X.NROEMPRESA AND N.NROCHECKOUT = X.NROCHECKOUT AND N.SEQDOCTO = Y.SEQDOCTO
   WHERE Y.DTAMOVIMENTO BETWEEN DATE '2025-01-01' AND SYSDATE
     AND Y.NROEMPRESA = 8
   GROUP BY TRUNC(Y.DTAMOVIMENTO, 'MM'))
   
SELECT TO_CHAR(I.MES, 'MM/YYYY') DATA,
       I.QTD_INUT,
       N.QTD_NORMAL, ROUND((I.QTD_INUT / QTD_NORMAL) * 100,2) PERC_INUT
  FROM INUT I LEFT JOIN NORMAL N ON N.MES = I.MES
 ORDER BY I.MES;
